export const plants = [
  {
    name: "Peace Lily Plant",
    price: "₹278",
    originalPrice: "₹350",
    discount: "21%",
    image: require("../assets/plants/Peace Lily Plant.png"),
    type: "plant",
  },
  {
    name: "Snake Plant",
    price: "₹350",
    originalPrice: "₹430",
    discount: "19%",
    image: require("../assets/plants/snakeplant.jpg"),
    type: "plant",
  },
  {
    name: "Spider Plant",
    price: "₹299",
    originalPrice: "₹400",
    discount: "25%",
    image: require("../assets/plants/spiderplant.jpg"),
    type: "plant",
  },
  {
    name: "Pothos Plant",
    price: "₹250",
    originalPrice: "₹320",
    discount: "22%",
    image: require("../assets/plants/pothosplant.jpg"),
    type: "plant",
  },
  {
    name: "Aloe Vera Plant",
    price: "₹320",
    originalPrice: "₹400",
    discount: "20%",
    image: require("../assets/plants/aloveraplant.jpg"),
    type: "plant",
  },
  {
    name: "Rubber Plant",
    price: "₹450",
    originalPrice: "₹600",
    discount: "25%",
    image: require("../assets/plants/rubberplant.jpg"),
    type: "plant",
  },
  {
    name: "Boston Fern",
    price: "₹380",
    originalPrice: "₹520",
    discount: "27%",
    image: require("../assets/plants/bostonfern.jpg"),
    type: "plant",
  },
  {
    name: "Chinese Evergreen",
    price: "₹300",
    originalPrice: "₹390",
    discount: "23%",
    image: require("../assets/plants/chineseevergreen.jpg"),
    type: "plant",
  },
  {
    name: "ZZ Plant",
    price: "₹399",
    originalPrice: "₹520",
    discount: "23%",
    image: require("../assets/plants/zzplant.jpg"),
    type: "plant",
  },
  {
    name: "Golden Pothos",
    price: "₹280",
    originalPrice: "₹400",
    discount: "30%",
    image: require("../assets/plants/goldenpothos.jpg"),
    type: "plant",
  },
  {
    name: "Philodendron Heartleaf",
    price: "₹340",
    originalPrice: "₹450",
    discount: "24%",
    image: require("../assets/plants/philodendronheartleaf.jpg"),
    type: "plant",
  },
  {
    name: "Dracaena Marginata",
    price: "₹420",
    originalPrice: "₹520",
    discount: "19%",
    image: require("../assets/plants/dracaenamarginata.png"),
    type: "plant",
  },
  {
    name: "Fiddle Leaf Fig",
    price: "₹599",
    originalPrice: "₹850",
    discount: "30%",
    image: require("../assets/plants/fiddleleaffig.jpg"),
    type: "plant",
  },
  {
    name: "Monstera Deliciosa",
    price: "₹480",
    originalPrice: "₹600",
    discount: "20%",
    image: require("../assets/plants/monsteradelicios.jpg"),
    type: "plant",
  },
  {
    name: "Calathea Triostar",
    price: "₹360",
    originalPrice: "₹480",
    discount: "25%",
    image: require("../assets/plants/calatheatriostar.jpg"),
    type: "plant",
  },
  {
    name: "Dwarf Schefflera",
    price: "₹250",
    originalPrice: "₹340",
    discount: "26%",
    image: require("../assets/plants/dwarfschefflera.jpg"),
    type: "plant",
  },
  {
    name: "Pilea Plant",
    price: "₹305",
    originalPrice: "₹400",
    discount: "24%",
    image: require("../assets/plants/pileaplant.jpg"),
    type: "plant",
  },
  {
    name: "Bonsai Tree",
    price: "₹650",
    originalPrice: "₹950",
    discount: "32%",
    image: require("../assets/plants/bonsaitree.jpg"),
    type: "plant",
  },
  {
    name: "Orchid",
    price: "₹400",
    originalPrice: "₹580",
    discount: "31%",
    image: require("../assets/plants/orchid.jpg"),
    type: "plant",
  },
];

export const seeds = [
  {
    name: "Blue Lotus Seeds",
    price: "₹150",
    originalPrice: "₹200",
    discount: "25%",
    image: require("../assets/rare-seeds/bluelotus.png"),
    type: "seed",
  },
  {
    name: "Baobab Tree Seeds",
    price: "₹180",
    originalPrice: "₹250",
    discount: "28%",
    image: require("../assets/rare-seeds/baobab.png"),
    type: "seed",
  },
  // {
  //   name: "Black Bamboo Seeds",
  //   price: "₹200",
  //   originalPrice: "₹280",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/blackbamboo.jpg"),
  //   type: "seed",
  // },
  // {
  //   name: "Dragon Blood Tree Seeds",
  //   price: "₹250",
  //   originalPrice: "₹350",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/dragonbloodtree.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Giant Sequoia Seeds",
  //   price: "₹300",
  //   originalPrice: "₹400",
  //   discount: "25%",
  //   image: require("../assets/rare-seeds/giantsequoia.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Welwitschia Seeds",
  //   price: "₹280",
  //   originalPrice: "₹370",
  //   discount: "24%",
  //   image: require("../assets/rare-seeds/welwitschia.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Ghost Orchid Seeds",
  //   price: "₹350",
  //   originalPrice: "₹500",
  //   discount: "30%",
  //   image: require("../assets/rare-seeds/ghostorchid.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Corpse Flower Seeds",
  //   price: "₹500",
  //   originalPrice: "₹700",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/corpseflower.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Himalayan Blue Poppy Seeds",
  //   price: "₹220",
  //   originalPrice: "₹300",
  //   discount: "27%",
  //   image: require("../assets/rare-seeds/bluepoppy.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "White Bat Plant Seeds",
  //   price: "₹320",
  //   originalPrice: "₹450",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/whitebatplant.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Rainbow Eucalyptus Seeds",
  //   price: "₹400",
  //   originalPrice: "₹550",
  //   discount: "27%",
  //   image: require("../assets/rare-seeds/rainboweucalyptus.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Pitcher Plant Seeds",
  //   price: "₹250",
  //   originalPrice: "₹350",
  //   discount: "28%",
  //   image: require("../assets/rare-seeds/pitcherplant.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Lithops (Living Stone) Seeds",
  //   price: "₹180",
  //   originalPrice: "₹250",
  //   discount: "28%",
  //   image: require("../assets/rare-seeds/lithops.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Frankincense Tree Seeds",
  //   price: "₹400",
  //   originalPrice: "₹550",
  //   discount: "27%",
  //   image: require("../assets/rare-seeds/frankincense.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Adenium Obesum Seeds",
  //   price: "₹200",
  //   originalPrice: "₹280",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/adeniumobesum.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Jade Vine Seeds",
  //   price: "₹350",
  //   originalPrice: "₹480",
  //   discount: "27%",
  //   image: require("../assets/rare-seeds/jadevine.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "African Tulip Tree Seeds",
  //   price: "₹180",
  //   originalPrice: "₹250",
  //   discount: "28%",
  //   image: require("../assets/rare-seeds/africantulip.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Rafflesia Seeds",
  //   price: "₹600",
  //   originalPrice: "₹850",
  //   discount: "29%",
  //   image: require("../assets/rare-seeds/rafflesia.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Bottle Tree Seeds",
  //   price: "₹250",
  //   originalPrice: "₹350",
  //   discount: "28%",
  //   image: require("../assets/rare-seeds/bottletree.jpg"),
    //   type: "seed",
  // },
  // {
  //   name: "Silk Floss Tree Seeds",
  //   price: "₹280",
  //   originalPrice: "₹400",
  //   discount: "30%",
  //   image: require("../assets/rare-seeds/silkfloss.jpg"),
    //   type: "seed",
  // },
];
